In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sp
import qutip as qt

## Quantum mechanical operators

### The two-level system

Let $\left| 1 \right>$ represent the atom in the excited state, and $\left| 0 \right>$ represent the atom in the ground state. The *lowering operator* $\sigma$ takes the excited state to the ground state. 

$$
\sigma \left| 1 \right> = \left| 0 \right>
$$

The *raising operator* $\sigma^\dagger$ does the opposite. 

$$
\sigma^\dagger \left| 0 \right> = \left| 1 \right>
$$

If you try to lower the ground state or raise the excited state you get nothing. 

$$
\begin{aligned}
\sigma \left| 0 \right> &= 0  \\
\sigma^\dagger \left| 1 \right> &= 0
\end{aligned}
$$

These operators and quantum states are best represented as matrices and vectore. 

$$
\begin{aligned}
\left|1\right\rangle &=
\left(\begin{array}{c}
1\\
0
\end{array}\right) \\

\left|0\right\rangle &=\left(\begin{array}{c}
0\\
1
\end{array}\right) \\

\sigma	&=\left(\begin{array}{cc}
0 & 0\\
1 & 0
\end{array}\right) \\
\sigma^{\dagger}	&=\left(\begin{array}{cc}
0 & 1\\
0 & 0
\end{array}\right)
\end{aligned}
$$

These can easily be implemented using QuTiP in Python!


In [7]:
# Excited state
# qt.tensor makes a quantum object
# qt.basis(N, M) makes a state with N-levels and puts you in the Mth level
# The way QuTiP is set up, M=0 is the excited state
psi1 = qt.tensor(qt.basis(2,0))
psi1

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]

In [6]:
# The lowering operator works as expected
# Lowering operator
sm = qt.sigmam()
sm

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[0. 0.]
 [1. 0.]]

In [8]:
# Unsurprisingly, when you multiply them together, you get the ground state
sm * psi1

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]

These can be generalized to very large states. For example, and atom with 4 levels in the 2nd level is as follows. 

In [12]:
psi = qt.tensor(qt.basis(4, 4 - 2))
psi

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [1.]
 [0.]]

### The Fock state

If you want more than just two states it's just as easy! A state with $n$ photons can be represented as $\left| n \right>$. The *destruction operator* $a$ takes you from $n$-many photons to $n-1$. In the case of an atom, you're just moving the electron from one state to another. But in the case of a Fock state, the operators create and destroy photons, so you get another factor $c_{n}$ out front. 

$$
\begin{aligned}
a \left| n \right> = c_{n-1} \left| n-1 \right> \\
a^\dagger \left| n \right> = c_{n+1} \left| n+1 \right> \\
\end{aligned}
$$

The following example is $\left| 4 \right>$. 

In [14]:
# We want a quantum state that can hold up to 10 photons.
# Because we also have the vacuum state, with no photons, we need 11 states total.
# In the case of photons, the states count up instead of down. I don't know why. 
N = 10  # Max number of photons
psi = qt.tensor(qt.basis(N, 4))

In [ ]:
# The destruction operator gets a special function
# This function destroys one photon
a = qt.destroy(N)